# Generated by Django 4.2.7 on 2023-12-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма оплаты'),
        ),
    ]
