# Generated by Django 4.2.7 on 2023-12-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='link_for_payment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Статус платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания оплаты'),
        ),
    ]
