# Generated by Django 4.2.7 on 2023-12-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_link_for_payment_payment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='Не оплачено', max_length=300, verbose_name='Статус платежа'),
        ),
    ]
