# Generated by Django 4.2.7 on 2023-12-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Id сессии платежа'),
        ),
    ]
