# Generated by Django 4.2.7 on 2023-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_payment_user_payment_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link_for_payment',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
