# Generated by Django 4.2.7 on 2023-11-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
