# Generated by Django 4.2.7 on 2023-12-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_course_datetime_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='datetime_last_update',
        ),
        migrations.AddField(
            model_name='course',
            name='is_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата/время последнего обновления'),
        ),
    ]
